### ISSUE TITLE
Validator set hash calculation error 

### ISSUE THREAD

**Issue by vidorge** [nomic-io/js-tendermint#20]
Hello,

I'm getting the following error

```
(node:73894) UnhandledPromiseRejectionWarning: Error: Validator set does not match what we expected
    at verifyValidatorSet (/Users/x/Development/project-name/node_modules/private-submodule-api/node_modules/tendermint/lib/verify.js:274:11)
    at new LightNode (/Users/x/Development/project-name/node_modules/private-submodule-api/node_modules/tendermint/lib/lightNode.js:69:5)
    at WrappedClass (/Users/x/Development/project-name/node_modules/old/lib/index.js:11:12)
    at /Users/x/Development/project-name/node_modules/private-submodule-api/dist/client.js:133:26
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/x/Development/project-name/node_modules/private-submodule-api/dist/client.js:3:103)
    at _next (/Users/x/Development/project-name/node_modules/private-submodule-api/dist/client.js:5:194)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

I'm using Tendermint v0.30.0-rc0 which doesn't have any validator hashing changes in comparison to v0.30.1.

This is the input validator list

 ```
[
    {
        "address": "1D171868FB701094EE4C457EE7BDF0D72041183C",
        "pub_key": {
            "type": "tendermint/PubKeyEd25519",
            "value": "ff9hfVq81gYUrElr9mJjZAzh3MMx3dDmCt9slX8EYx8="
        },
        "voting_power": 2000000,
        "proposer_priority": "0"
    }
]
```

And this is the expected validator hash that I got for the same height:
`validators_hash: "4E99A1CD196DD132623DAF35A8EC8E143A9B892EED3580148C71C5FD50D43916"`

While troubleshooting intermediary steps i got to the conclusion that the encoded hex bytes of the tendermint and js-tendermint implementation of encoding validators differ:

Tendermint (tendermint/tendermint/types/validator_set.go::Hash logging `bzs[0]`)
`0a 25 16 24 de 64 20 7d ff 61 7d 5a bc d6 06 14 ac 49 6b f6 62 63 64 0c e1 dc c3 31 dd d0 e6 0a df 6c 95 7f 04 63 1f 10 80 89 7a`

js-tendermint (`getValidatorSetHash` logging `bytes` variable)
`0a 25 16 24 de 64 20 7d ff 61 7d 5a bc d6 06 14 ac 49 6b f6 62 63 64 0c e1 dc c3 31 dd d0 e6 0a df 6c 95 7f 04 63 1f 10 80 89 7a 00`

Any suggestions?
Thanks.

**Comment by mappum** [comment]
Thanks for including the different encoding outputs, that helped a lot!

The bug is now fixed and published in `js-tendermint@4.0.2` (597f2c4488f719af05d28b8c3b8a59c5df8f441b), and a test fixture was added.
