### ISSUE TITLE
Error on syncTo with Tendermint v0.33.0

### ISSUE THREAD

**Issue by michaelfig** [nomic-io/js-tendermint#25]
I have a Javascript user of js-tendermint that no longer works since I upgraded cosmos-sdk from v0.37.x to [ibc-alpha](https://github.com/Cosmos/cosmos-sdk/tree/ibc-alpha) (which is destined to become part of v0.39.0).  These changes are part of [Tendermint v0.33.0](https://github.com/tendermint/tendermint/releases/tag/v0.33.0).

<details>
<summary>Here is the relevant sources</summary>
```js
      const nodeAddr = `ws://${rpcAddr}`;
      const rpc = Tendermint.RpcClient(nodeAddr);
      const { genesis } = await rpc.genesis();
      const { validators } = await rpc.validators({
        height: LAST_KNOWN_BLOCKHEIGHT,
      });
      rpc.close();
      if (genesis.chain_id !== chainID) {
        throw Error(
          `downloaded chainID ${genesis.chain_id} does not match expected chainID ${chainID}`,
        );
      }
      const gci = createHash('sha256')
        .update(djson.stringify(genesis))
        .digest('hex');
      if (gci !== GCI) {
        throw Error(`computed GCI ${gci} does not match expected GCI ${GCI}`);
      }
      const clientState = {
        validators,
        commit: LAST_KNOWN_COMMIT,
        header: { height: LAST_KNOWN_BLOCKHEIGHT, chain_id: chainID },
      };
      const client = Tendermint(nodeAddr, clientState);
      return new Promise((resolve, reject) => {
        client.once('error', reject);
        client.once('synced', () => {
          client.removeListener('error', reject);
          resolve({ lightClient: client });
        });
      });
```
</details>

<details>
<summary>The old output of `curl http://$rpcaddr/commit?height=1 | jq -S .`</summary>
```json
{
  "id": "",
  "jsonrpc": "2.0",
  "result": {
    "canonical": true,
    "signed_header": {
      "commit": {
        "block_id": {
          "hash": "8615E3503F09F7A352BD520E5C18B624C3DE48786D219DDC08DB1335D19DE3BF",
          "parts": {
            "hash": "BFB51A7224982E898DC0238A27CAC16458FF1E2784D3119D2C37DE5F858D8234",
            "total": "1"
          }
        },
        "precommits": [
          {
            "block_id": {
              "hash": "8615E3503F09F7A352BD520E5C18B624C3DE48786D219DDC08DB1335D19DE3BF",
              "parts": {
                "hash": "BFB51A7224982E898DC0238A27CAC16458FF1E2784D3119D2C37DE5F858D8234",
                "total": "1"
              }
            },
            "height": "1",
            "round": "0",
            "signature": "uAgZkMaxBw/mlKyNDzvQqgDzElKvv3v7sbAf7vOUOCOrn4mKSwPDdqXWhyl/AW2hbWjQ+IqRyiCpR1ggbrvjDQ==",
            "timestamp": "2020-02-05T18:06:33.278590237Z",
            "type": 2,
            "validator_address": "B6E6C700D11BBE7C985947C8032D5BC727B159B4",
            "validator_index": "0"
          }
        ]
      },
      "header": {
        "app_hash": "",
        "chain_id": "testnet-1.16.9",
        "consensus_hash": "048091BC7DDC283F77BFBF91D73C44DA58C3DF8A9CBC867405D8B7F3DAADA22F",
        "data_hash": "",
        "evidence_hash": "",
        "height": "1",
        "last_block_id": {
          "hash": "",
          "parts": {
            "hash": "",
            "total": "0"
          }
        },
        "last_commit_hash": "",
        "last_results_hash": "",
        "next_validators_hash": "D4DC7145A28290A04B4E75FBBF273C57AE0C09C0465A690953A471D986CF2551",
        "num_txs": "0",
        "proposer_address": "B6E6C700D11BBE7C985947C8032D5BC727B159B4",
        "time": "2020-01-16T18:38:45.449057712Z",
        "total_txs": "0",
        "validators_hash": "D4DC7145A28290A04B4E75FBBF273C57AE0C09C0465A690953A471D986CF2551",
        "version": {
          "app": "0",
          "block": "10"
        }
      }
    }
  }
}
```
</details>

<details>
<summary>The new output of `curl http://$rpcaddr/commit?height=1 | jq -S .`</summary>
```json
{
  "id": -1,
  "jsonrpc": "2.0",
  "result": {
    "canonical": true,
    "signed_header": {
      "commit": {
        "block_id": {
          "hash": "71F5F03990EA4536A374EB23E54C6910336D35A4862FE336FB7795AEEC498C64",
          "parts": {
            "hash": "BA88C4AB6E26AC489E0E9D0898C79F64CD979396B6736980CEDD3FA4BDCBADC7",
            "total": "1"
          }
        },
        "height": "1",
        "round": "0",
        "signatures": [
          {
            "block_id_flag": 2,
            "signature": "vVUE95CSa72VVzZa81efJY09dyRp5IvkGsbkuXNvuATbbjtEuwBDQK9fgYx120zajpAZn3jacupeXkqlmHG3Cg==",
            "timestamp": "2020-02-13T18:19:44.991611Z",
            "validator_address": "0D558E91691097C3442A3A36FABF9DA92F06AEFF"
          }
        ]
      },
      "header": {
        "app_hash": "",
        "chain_id": "agoric",
        "consensus_hash": "048091BC7DDC283F77BFBF91D73C44DA58C3DF8A9CBC867405D8B7F3DAADA22F",
        "data_hash": "",
        "evidence_hash": "",
        "height": "1",
        "last_block_id": {
          "hash": "",
          "parts": {
            "hash": "",
            "total": "0"
          }
        },
        "last_commit_hash": "",
        "last_results_hash": "",
        "next_validators_hash": "78ADAB44B7A42EED8EA88B7AF2780E0DD65B7C6C79C12E0B3A280584A62F5F28",
        "proposer_address": "0D558E91691097C3442A3A36FABF9DA92F06AEFF",
        "time": "2020-02-13T18:19:19.511558Z",
        "validators_hash": "78ADAB44B7A42EED8EA88B7AF2780E0DD65B7C6C79C12E0B3A280584A62F5F28",
        "version": {
          "app": "0",
          "block": "10"
        }
      }
    }
  }
}
```
</details>

I see structural differences, such as the removal of `"precommits"` and the following fields from `result.signed_header`:
```
-            "signature": "uAgZkMaxBw/mlKyNDzvQqgDzElKvv3v7sbAf7vOUOCOrn4mKSwPDdqXWhyl/AW2hbWjQ+IqRyiCpR1ggbrvjDQ==",
-            "timestamp": "2020-02-05T18:06:33.278590237Z",
-            "type": 2,
-            "validator_address": "B6E6C700D11BBE7C985947C8032D5BC727B159B4",
-            "validator_index": "0"
```

and the addition of `result.signed_header.signatures`.

<details><summary>The `diff -bu old.json new.json` between the two</summary>

```diff
--- old.json	2020-02-13 12:42:39.000000000 -0600
+++ new.json	2020-02-13 12:47:02.000000000 -0600
@@ -1,39 +1,31 @@
 {
-  "id": "",
+  "id": -1,
   "jsonrpc": "2.0",
   "result": {
     "canonical": true,
     "signed_header": {
       "commit": {
         "block_id": {
-          "hash": "8615E3503F09F7A352BD520E5C18B624C3DE48786D219DDC08DB1335D19DE3BF",
+          "hash": "71F5F03990EA4536A374EB23E54C6910336D35A4862FE336FB7795AEEC498C64",
           "parts": {
-            "hash": "BFB51A7224982E898DC0238A27CAC16458FF1E2784D3119D2C37DE5F858D8234",
-            "total": "1"
-          }
-        },
-        "precommits": [
-          {
-            "block_id": {
-              "hash": "8615E3503F09F7A352BD520E5C18B624C3DE48786D219DDC08DB1335D19DE3BF",
-              "parts": {
-                "hash": "BFB51A7224982E898DC0238A27CAC16458FF1E2784D3119D2C37DE5F858D8234",
+            "hash": "BA88C4AB6E26AC489E0E9D0898C79F64CD979396B6736980CEDD3FA4BDCBADC7",
                 "total": "1"
               }
             },
             "height": "1",
             "round": "0",
-            "signature": "uAgZkMaxBw/mlKyNDzvQqgDzElKvv3v7sbAf7vOUOCOrn4mKSwPDdqXWhyl/AW2hbWjQ+IqRyiCpR1ggbrvjDQ==",
-            "timestamp": "2020-02-05T18:06:33.278590237Z",
-            "type": 2,
-            "validator_address": "B6E6C700D11BBE7C985947C8032D5BC727B159B4",
-            "validator_index": "0"
+        "signatures": [
+          {
+            "block_id_flag": 2,
+            "signature": "vVUE95CSa72VVzZa81efJY09dyRp5IvkGsbkuXNvuATbbjtEuwBDQK9fgYx120zajpAZn3jacupeXkqlmHG3Cg==",
+            "timestamp": "2020-02-13T18:19:44.991611Z",
+            "validator_address": "0D558E91691097C3442A3A36FABF9DA92F06AEFF"
           }
         ]
       },
       "header": {
         "app_hash": "",
-        "chain_id": "testnet-1.16.9",
+        "chain_id": "testnet-1.17.0",
         "consensus_hash": "048091BC7DDC283F77BFBF91D73C44DA58C3DF8A9CBC867405D8B7F3DAADA22F",
         "data_hash": "",
         "evidence_hash": "",
@@ -47,12 +39,10 @@
         },
         "last_commit_hash": "",
         "last_results_hash": "",
-        "next_validators_hash": "D4DC7145A28290A04B4E75FBBF273C57AE0C09C0465A690953A471D986CF2551",
-        "num_txs": "0",
-        "proposer_address": "B6E6C700D11BBE7C985947C8032D5BC727B159B4",
-        "time": "2020-01-16T18:38:45.449057712Z",
-        "total_txs": "0",
-        "validators_hash": "D4DC7145A28290A04B4E75FBBF273C57AE0C09C0465A690953A471D986CF2551",
+        "next_validators_hash": "78ADAB44B7A42EED8EA88B7AF2780E0DD65B7C6C79C12E0B3A280584A62F5F28",
+        "proposer_address": "0D558E91691097C3442A3A36FABF9DA92F06AEFF",
+        "time": "2020-02-13T18:19:19.511558Z",
+        "validators_hash": "78ADAB44B7A42EED8EA88B7AF2780E0DD65B7C6C79C12E0B3A280584A62F5F28",
         "version": {
           "app": "0",
           "block": "10"
```

</details>

I will be able to dig into this later, just wanted to make it known this is an issue (and hopefully is already addressed).

Here is the error message:

```
adding follower/sender for GCI af14d3fb3188480b65bf9f64fdf8a3d99ea05537f56e97ff93a46b5d2d484b2a
Listening on 127.0.0.1:8000
Error: Value undefined is not an integer in the valid range
    at safeParseInt (/Users/michael/agoric/agoric-sdk/node_modules/tendermint/lib/common.js:6:11)
    at encodingLength (/Users/michael/agoric/agoric-sdk/node_modules/tendermint/lib/varint.js:35:9)
    at Object.encode (/Users/michael/agoric/agoric-sdk/node_modules/tendermint/lib/varint.js:15:99)
    at getBlockHash (/Users/michael/agoric/agoric-sdk/node_modules/tendermint/lib/hash.js:20:156)
    at verifyCommit (/Users/michael/agoric/agoric-sdk/node_modules/tendermint/lib/verify.js:53:19)
    at verify (/Users/michael/agoric/agoric-sdk/node_modules/tendermint/lib/verify.js:299:3)
    at LightNode.update (/Users/michael/agoric/agoric-sdk/node_modules/tendermint/lib/lightNode.js:248:7)
    at LightNode.syncTo (/Users/michael/agoric/agoric-sdk/node_modules/tendermint/lib/lightNode.js:157:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async LightNode.initialSync (/Users/michael/agoric/agoric-sdk/node_modules/tendermint/lib/lightNode.js:135:9)
```

**Comment by michaelfig** [comment]
I've now seen the same errors as early as cosmos-sdk v0.38.0

**Comment by jackzampolin** [comment]
I think the branch we want to target for updates is `ibc-alpha` which also includes all the `.proto` changes. Maybe a final approach here is going to be determined by the proto meeting later this week.

**Comment by mappum** [comment]
Hey @michaelfig, sorry I missed this one.

I'll work on making sure this is compatible with recent Tendermint versions.

**Comment by michaelfig** [comment]
No problem.  With my hacks, it works for me, but you are probably going to want to factor it better.
